require("functionality.theme").enable()
require("functionality.keys").enable()
require("functionality.system").enable()
require("functionality.text").enable()
require("functionality.git").enable()
require("functionality.lsp").enable()
